name: check-python-linter
on:
  push:
jobs:
  check-python-format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Ruff action
        uses: chartboost/ruff-action@v1
        with:
          version: 0.4.10
          args: 'check'
