name: push-docker-image
on:
  push:
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.6
      - name: Setup docker-buildx
        uses: docker/setup-buildx-action@v3.3.0
      - name: Login to ghcr.io
        uses: docker/login-action@v3.2.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Create a metadata
        uses: docker/metadata-action@v5.5.1
        id: meta
        with:
          tags: |
            type=ref,event=tag
            type=raw,value=ghcr.io/${{ github.repository }}:main-{{sha}}
      - name: Build docker-image and push to ghcr.io
        uses: docker/build-push-action@v6.2.0
        with:
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
